apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-controller-clusterrole
  namespace: default
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "secrets"]
  verbs: ["*"]
- apiGroups: ["vault.iti.com"]
  resources: ["vault-connections"]
  verbs: ["*"]
- apiGroups: ["vault.iti.com"]
  resources: ["vault-secrets"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-controller-ClusterRoleBinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: vault-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: vault-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-controller
  labels:
    name: vault-controller
spec:
  serviceAccountName: vault-controller
  containers:
  - name: vault-controller
    image: ghcr.io/danielfarag/k8s-vault-controller:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
